#!/usr/bin/env python3
"""Regenerate netlify/functions/lib/journalfonts.mjs — the Latin-subset, base64
brand fonts embedded in the Journal Pin renderer (netlify/functions/lib/journalpin.mjs).

Titles use Noto Serif TC (weight 500); everything else uses Cabin (400 / 500 / 600).
Embedding them (like fonts.mjs / pinfonts.mjs) means the Netlify function has no
font-file/bundling dependency at runtime.

Requires: fontTools  (pip install fonttools).  Run from the repo root:
    python scripts/subset-journal-fonts.py

Sources:
  • NotoSerifTC-Medium.ttf — expected in the repo root (brand font handoff).
  • Cabin[wdth,wght].ttf   — auto-downloaded from Google Fonts if not cached locally,
                             then instanced to wght 400/500/600 at wdth 100.
"""
import base64
import io
import os
import sys
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "netlify", "functions", "lib", "journalfonts.mjs")
CABIN_VF = os.path.join(REPO, "scripts", ".cache-Cabin.ttf")
CABIN_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/cabin/Cabin%5Bwdth,wght%5D.ttf"
NOTO_TC = os.path.join(REPO, "NotoSerifTC-Medium.ttf")

# Latin + Latin-1 + the punctuation the pins actually use (curly quotes, en/em
# dash, middot "·", ellipsis, bullet). Kept tight so the embedded fonts stay small.
UNICODES = "U+0020-00FF,U+2010-2015,U+2018-201F,U+2022,U+2026,U+2039-203A,U+00B7,U+00A0"


def subset_font(font):
    opts = subset.Options()
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    ss = subset.Subsetter(options=opts)
    ss.populate(unicodes=subset.parse_unicodes(UNICODES))
    ss.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def ensure_cabin():
    if not os.path.exists(CABIN_VF):
        print("downloading Cabin variable font...")
        urllib.request.urlretrieve(CABIN_URL, CABIN_VF)
    return CABIN_VF


def cabin_instance(weight):
    f = TTFont(ensure_cabin())
    instantiateVariableFont(f, {"wght": weight, "wdth": 100}, inplace=True)
    return subset_font(f)


def main():
    if not os.path.exists(NOTO_TC):
        sys.exit(f"missing {NOTO_TC} — put NotoSerifTC-Medium.ttf in the repo root")
    results = {}
    for w, name in [(400, "CABIN_400"), (500, "CABIN_500"), (600, "CABIN_600")]:
        results[name] = cabin_instance(w)
        print(name, len(results[name]), "bytes")
    results["NOTO_SERIF_TC_500"] = subset_font(TTFont(NOTO_TC))
    print("NOTO_SERIF_TC_500", len(results["NOTO_SERIF_TC_500"]), "bytes")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by scripts/subset-journal-fonts.py (do not hand-edit).\n")
        fh.write("// Brand pin fonts, Latin-subset & embedded as base64 so the Netlify\n")
        fh.write("// function has no path/bundling dependency. Noto Serif TC (titles, wt 500)\n")
        fh.write("// + Cabin (eyebrow 600 / meta 500 / excerpt & url 400).\n")
        for name, data in results.items():
            b64 = base64.b64encode(data).decode("ascii")
            fh.write(f'export const {name} = Buffer.from("{b64}", "base64");\n')
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
