// GENERATED by scripts/gen-immersive-heights.mjs — do not edit by hand.
//
// The tallest full-width photograph each pose can carry in the Immersive
// template without losing an end of her. 1500 means full bleed.
//
// Measured against the untrimmed 1400×933 frame in public/poses/, which is what
// Immersive reads — not the tight crop in public/poses/pin/ that poseFrames.ts
// describes. The two disagree, and this is the one that matters here.

/** Below this the photograph can't reach the type, and Panel takes the pose. */
export const IMMERSIVE_FLOOR = 1000;

export const POSE_TALL: Record<string, number> = {
  'ankle-stretch': 958,
  'banana': 963,
  'bow-tie': 769,
  'broken-wing': 1094,
  'butterfly': 1344,
  'camel': 1081,
  'cat-pulling-its-tail': 949,
  'caterpillar': 1372,
  'childs-pose': 995,
  'corpse': 920,
  'cow-face': 1500,
  'dangling': 1500,
  'deer': 1218,
  'dragon': 824,
  'dragonfly': 1069,
  'eagle': 1052,
  'easy-pose': 1047,
  'folded-half-shoelace': 1121,
  'frog': 1486,
  'half-butterfly': 976,
  'happy-baby': 1312,
  'legs-up-the-wall': 1500,
  'melting-heart': 1148,
  'reclined-swan': 1053,
  'reclined-twist': 862,
  'saddle': 1034,
  'seal': 1289,
  'shoelace': 1016,
  'sleeping-swan': 744,
  'sphinx': 797,
  'squat': 1500,
  'supported-bridge': 936,
  'supported-fish': 788,
  'swan': 830,
  'thread-the-needle': 1202,
  'toe-squat': 884,
  'twisted-dragon': 950,
};

/** How tall Immersive's photograph may be, or 0 if this pose can't carry one. */
export const immersiveHeight = (slug: string): number => {
  const h = POSE_TALL[slug];
  return h !== undefined && h >= IMMERSIVE_FLOOR ? h : 0;
};
