// GENERATED by scripts/gen-pin-crops.mjs — do not edit by hand.
//
// One row per pose photo in public/poses/pin/, which is the subject-centred crop
// every pin template reads.
//
//   aspect — the crop's width / height
//   span   — how much of that width Katie occupies, 0–1
//
// A portrait template keeps `targetAspect / aspect` of the width. If that is
// less than `span`, the crop cuts into her, and the template is not eligible
// for that pose. src/lib/pinInventory.ts does the arithmetic; nothing here is a
// judgement call.

export type PoseFrame = { aspect: number; span: number };

export const POSE_FRAMES: Record<string, PoseFrame> = {
  'ankle-stretch': {
    'aspect': 1.333,
    'span': 0.783
  },
  'banana': {
    'aspect': 1.482,
    'span': 0.701
  },
  'bow-tie': {
    'aspect': 1.303,
    'span': 0.998
  },
  'broken-wing': {
    'aspect': 1.487,
    'span': 0.615
  },
  'butterfly': {
    'aspect': 1.468,
    'span': 0.507
  },
  'camel': {
    'aspect': 1.262,
    'span': 0.733
  },
  'cat-pulling-its-tail': {
    'aspect': 1.497,
    'span': 0.704
  },
  'caterpillar': {
    'aspect': 1.496,
    'span': 0.487
  },
  'childs-pose': {
    'aspect': 1.376,
    'span': 0.731
  },
  'corpse': {
    'aspect': 1.387,
    'span': 0.784
  },
  'cow-face': {
    'aspect': 1.482,
    'span': 0.338
  },
  'dangling': {
    'aspect': 1.501,
    'span': 0.37
  },
  'deer': {
    'aspect': 1.32,
    'span': 0.622
  },
  'dragon': {
    'aspect': 1.421,
    'span': 0.854
  },
  'dragonfly': {
    'aspect': 1.459,
    'span': 0.641
  },
  'eagle': {
    'aspect': 1.3,
    'span': 0.731
  },
  'easy-pose': {
    'aspect': 1.26,
    'span': 0.758
  },
  'folded-half-shoelace': {
    'aspect': 1.483,
    'span': 0.601
  },
  'frog': {
    'aspect': 1.492,
    'span': 0.451
  },
  'half-butterfly': {
    'aspect': 1.308,
    'span': 0.784
  },
  'happy-baby': {
    'aspect': 1.296,
    'span': 0.588
  },
  'legs-up-the-wall': {
    'aspect': 1.496,
    'span': 0.409
  },
  'melting-heart': {
    'aspect': 1.277,
    'span': 0.683
  },
  'reclined-swan': {
    'aspect': 1.486,
    'span': 0.639
  },
  'reclined-twist': {
    'aspect': 1.468,
    'span': 0.79
  },
  'saddle': {
    'aspect': 1.26,
    'span': 0.767
  },
  'seal': {
    'aspect': 1.295,
    'span': 0.599
  },
  'shoelace': {
    'aspect': 1.271,
    'span': 0.774
  },
  'sleeping-swan': {
    'aspect': 1.438,
    'span': 0.934
  },
  'sphinx': {
    'aspect': 1.441,
    'span': 0.871
  },
  'squat': {
    'aspect': 1.49,
    'span': 0.371
  },
  'supported-bridge': {
    'aspect': 1.499,
    'span': 0.713
  },
  'supported-fish': {
    'aspect': 1.269,
    'span': 1
  },
  'swan': {
    'aspect': 1.501,
    'span': 0.803
  },
  'thread-the-needle': {
    'aspect': 1.288,
    'span': 0.646
  },
  'toe-squat': {
    'aspect': 1.26,
    'span': 0.898
  },
  'twisted-dragon': {
    'aspect': 1.38,
    'span': 0.762
  }
};
